version: '3'
services:
  app:
    container_name: dyglxt
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/sqlite.db
      - JWT_SECRET=change-me-in-prod
    restart: always
